import Navbar from "@/components/navbar";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "Reddit App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Suspense fallback={<Loading />}>
          <main className="bg-gray-400/75">{children}</main>
        </Suspense>
      </body>
    </html>
  );
}
